# name of your application
APPLICATION = Task02

# default BOARD
BOARD ?= pba-d-01-kw2x

USEMODULE += xtimer

# RIOT base directory
RIOTBASE ?= $(CURDIR)/../RIOT

include $(RIOTBASE)/Makefile.include
