# name of your application
APPLICATION = Task05

# default BOARD
BOARD ?= pba-d-01-kw2x

USEMODULE += shell
USEMODULE += shell_commands

# RIOT base directory
RIOTBASE ?= $(CURDIR)/../RIOT

include $(RIOTBASE)/Makefile.include
